### ISSUE TITLE
La página de Redsys me retorna error de importe 0

### ISSUE THREAD

**Issue by Kyosfonica** [ssheduardo/redsys-laravel#10]
He implementado el código del ejemplo y he cambiado los datos por los de prueba que vienen en el manual del Sabadell y al pulsar en el botón send me aparece la web de Redsys con el importe a 0 y con el mensaje: Error en datos enviados. Contacte con su comercio.

En la web no hay ningún tag --SIS que muestre errores y con los datos que tengo en el manual el panel de administración del entorno de pruebas da error al hacer login...

Estos son los datos que se generan en el formulario:

Redsys::getParameters() = {array} [14]
 DS_MERCHANT_AMOUNT = 500
 DS_MERCHANT_ORDER = "1498734164"
 DS_MERCHANT_MERCHANTCODE = "327234688"
 DS_MERCHANT_CURRENCY = "978"
 DS_MERCHANT_TRANSACTIONTYPE = "0"
 DS_MERCHANT_TERMINAL = "001"
 DS_MERCHANT_PAYMETHODS = "T"
 DS_MERCHANT_MERCHANTURL = ""
 DS_MERCHANT_URLOK = ""
 DS_MERCHANT_URLKO = ""
 DS_MERCHANT_MERCHANTNAME = "Tienda S.L"
 DS_MERCHANT_TITULAR = "Pedro Risco"
 DS_MERCHANT_PRODUCTDESCRIPTION = "Compras varias"
 DS_MERCHANT_MERCHANTDATA = "30"

También he probado con el Terminal a 1 en lugar de a 001 (aunque el manual dice que debe ser 001) y aparece el mismo error.

¿Alguna idea de que puede ser?

**Comment by ssheduardo** [comment]
Hola,
Lo acabo de probar y funciona, una cosa has configurado el archivo redsys.php (config/redsys.php)
Con los datos:
```
return [
    'key'                   => 'sq7HjrUOBfKmC576ILgskD5srU870gJ7',
    'url_notification'      => 'http://localhost/noti.php',
    'url_ok'                => 'http://localhost/ok.php',
    'url_ko'                => 'http://localhost/ko.php',
];

La llave key para pruebas es esa.

```

**Comment by Kyosfonica** [comment]
Hola,

Tienes toda la razón. Pensaba que el campo key era para la clave privada sin encriptar y estaba usando la clave privada de prueba qwertyasdf0123456789.

Ahora ya me ha funcionado. Cuando tenga la clave definitiva, ¿la dan ya calculada o la he de calcular yo?

Gracias.

**Comment by ssheduardo** [comment]
Creo que te la dan calculada
