### ISSUE TITLE
Duda al recibir datos

### ISSUE THREAD

**Issue by kezern** [ssheduardo/redsys-laravel#11]
Hola, lo primero felicidades por tu trabajo, gracias a ti, la instalación ha sido muy sencilla y funciona perfectamente.
Sólo me queda una cosa. He configurado el fichero redsys.php para que la url_ok sea www.midominio.com/urlok.
Según la documentación de redsys, se debería devolver información mediante post.
Tengo las siguientes rutas a modo de prueba en el web.php
Route::get('/urlok', function () {
	return "pago ok";
});

Route::post('/urlok', function () {
	return "pago ok post";
});

Siempre se está ejecutando la ruta por get.
Me gustaría obtener la información que viene de vuelta.

Un saludo

**Comment by ssheduardo** [comment]
Hola,
Muchas veces da a confusión esa url de ok, esta url se usa para pasar datos simples o un simple mensaje diciendo que se ha realizado correctamente el pago, donde debes devolver los datos por POST es a la url de notificación, en la página puedes ver un ejemplo.

**Comment by kezern** [comment]
Disculpa,pero no sé a qué página de ejemplo te refieres.
En la URL de notificación tengo la URL que me han dado desde redsys de realizar pago.

**Comment by kezern** [comment]
Creo que he localizado parte de mi problema, 
Como url_notification había puesto la del entorno de prueba de redsys "https://sis-t.redsys.es:25443/sis/realizarPago".
Sin embargo ahí tengo que poner la url en la que quiero recoger la respuesta post.
he puesto http://www.midominio.com/urlnotificacion y en las rutas del web.php 
Route::post('/urlnotificacion', 'RedsysController@notificacionPost');

Route::get('/urlnotificacion', 'RedsysController@notificacion');

Sin embargo los métodos que he creado en ese controlador no se ejecutan. He puesto para que me cree una entrada en la base de datos.
Hay algo que se me escapa no doy con la clave.
¿Me puedes guiar un poco por favor?

**Comment by ssheduardo** [comment]
Es muy fácil, primero prueba con postman, curl, etc el hacer el llamado por POST de la ruta que has creado para ver si realmente esta funcionando.

**Comment by kezern** [comment]
Hola,
Si, ya he hecho la prueba, hago una llamada a la ruta pasando por parámetro un nombre, en la ruta obtengo la request y hago la prueba a insertar le nombre en la base de datos. Todo me va ok.
Estoy casi seguro que es alguna tontería que se me escapa. El pago en redsys se hace correctamente, luego me devuelve a la ruta que he puesto como url_ok, pero esta respuesta no tiene parámetros, o no lo parece. Entiendo que los parámetros se devuelven por POST a la ruta notification_url. Lo que quiero es saber que pedido es el que se ha realizado para poder marcarlo como completado en mi base de datos.

**Comment by ssheduardo** [comment]
Lo estas probando en el entorno de test me imagino, que versión de laravel usas?

**Comment by kezern** [comment]
entorno test si y uso laravel 5.4

**Comment by ssheduardo** [comment]
Voy a ver si puedo instalar todo el entorno

**Comment by kezern** [comment]
Muchas gracias, te lo agradezco.
He intentado montar un entorno con laravel 5.3 a ver si podía ser problema de la versión, pero me ocurre exactamente lo mismo.

**Comment by kezern** [comment]
He estado probando y no es cosa de laravel. He probado con tu clase. La que has hecho para php y tengo el mismo problema. La llamada a la URL de notificación parece que no se está realizando.

**Comment by ssheduardo** [comment]
Es muy raro, yo tengo una demo de mi clase en php y funcionando hasta ahora.
Mira acabo de hacer la prueba y funcionando

```
Array
(
    [Ds_Date] => 09/08/2017
    [Ds_Hour] => 00:23
    [Ds_SecurePayment] => 1
    [Ds_Card_Number] => 454881******0004
    [Ds_ExpiryDate] => 2012
    [Ds_Merchant_Identifier] => cd8e4017c4c2f16bc9ccff87b0d07ad9c6cbd257
    [Ds_Card_Country] => 724
    [Ds_Amount] => 36100
    [Ds_Currency] => 978
    [Ds_Order] => 1502231006
    [Ds_MerchantCode] => 999008881
    [Ds_Terminal] => 001
    [Ds_Response] => 0000
    [Ds_MerchantData] => Descripcion_del_pedido_extra
    [Ds_TransactionType] => 0
    [Ds_ConsumerLanguage] => 1
    [Ds_AuthorisationCode] => 999191
    [Ds_Card_Brand] => 1
)
```

**Comment by kezern** [comment]
Pues no se que pasa, estoy en la web de redsys de notificaciones y parece que la manda, aparece como código 200 una notificación http asíncrona

**Comment by ssheduardo** [comment]
Pues no se en el entorno de test funciona el código sin problemas.

**Comment by miqfrontera** [comment]
Hola,
Nosotros tenemos una aplicación PHP que utiliza Redsys. Estamos migrando la aplicación a laravel, por eso estoy suscrito a los feeds de este proyecto.

El tema es que si no recuerdo mal, redsys, cuando finaliza el pago y todo ha ido bien, no te responde mediante POST sinó mediante GET.

Con lo que imagino que si en web.php no defines la url_ok como get, no debe llamarla. ¿Has probado a cambiar esto a ver si así te funciona?

**Comment by ssheduardo** [comment]
No hay que confundirse la url ok que es de tipo get es solo para mostrar que la transacción se ha realizado correctamente, y por el método POST te pasa todos los datos de necesarios para poder marcar en tu bbdd que dicha compra se ha realizado correctamente, imagina si usas el método get, cualquiera podría cambiar los datos y asignarse otras compras.

**Comment by ssheduardo** [comment]
Una cosa @kezern , las pruebas las estas realizando en un servidor o en tu ordenador?

**Comment by miqfrontera** [comment]
Por get pero encriptados. Así lo recibimos nosotros, y con la clave que nos da redsys, desencriptamos todos los parámetros de la transacción. Pero bueno, no sé como está montada la librería, no la hemos usado aún. Y puede ser que haya cambiado Redsys y ahora envíe por post. Solamente lo decía por probar y ayudar ;-)

**Comment by ssheduardo** [comment]
@miqfrontera recomiendo usar la URL de notificación que va por POST y va ser mucho más seguro que usar la url OK

**Comment by kezern** [comment]
Tengo un equipo que hace de servidor y tengo el puerto 80 del router abierto hacia ese equipo. Así que entiendo que es como un servidor normal (tengo un sistema de ddns).
He conseguido que la clase php me funcione correctamente, me devuelve los tres parámetros Ds_SignatureVersion, Ds_MerchantParameters y Ds_Signature.
Ahora estoy viendo que pasa con laravel, en la web de redsys cuando devuelve la petición a laravel, se muestra error 500 pero sin más información. Estoy mirando los logs de apache y tengo lo mismo.
[09/Aug/2017:10:48:27 +0200] "POST /urlnotificacion HTTP/1.0" 500 125676 "-" "Java/1.7.0"
Así que la respuesta me llega, pero algo tengo ya sea en mis rutas o en el controlador que estoy haciendo mal.

En la ruta tengo esto
Route::post('/urlnotificacion', 'RedsysController@notificacionPost');

y esa función en el controlador
public function notificacionPost(Request $request){
        $customer = new Customer();
        //$customer->name=$request->input('name');
        $customer->name="prueba";
        $customer->save();

        //return "notificacion push ok";
    }

**Comment by kezern** [comment]
Localizado el problema, mediante logs me he dado cuenta que un parámetro no se estaba obteniendo bien.
Ahora me queda una duda. He obtenido los datos de la respuesta mediante 
$parameters = Redsys::getMerchantParameters($request->input('Ds_MerchantParameters'));

¿Cómo puedo saber a que compra pertenece?
Supongamos que me hacen dos compras, recibiré dos respuestas independientes, cómo puedo saber a que compra corresponde cada respuesta?

Un saludo

**Comment by ssheduardo** [comment]
Genial, descartamos que sea error del módulo.
Cierro este issues

**Comment by kezern** [comment]
Muchas gracias, abro uno nuevo para la otra duda
