### ISSUE TITLE
Verificar un pedido

### ISSUE THREAD

**Issue by kezern** [ssheduardo/redsys-laravel#12]
Hola,
Ya tengo el módulo funcionando, me queda un último paso.
A partir del formulario se realiza un pedido, se envía para el pago con tarjeta y se revuelve una respuesta.
He estado mirando los valores que devuelve redsys pero no encuentro nada que me ayude a indentificar el pedido al que corresponde la respuesta. Es cierto que hay un campo llamado Ds_Order que tiene un número de pedido que imagino que se lo asigna redsys automáticamente, pero a mi no me permite vincularlo con el pedido realizado en el formulario original.
Lo que quiero es que cuando se rellene el formulario dicho pedido se marque como pendiente y marcarlo como completado al recibir la respuesta de redsys.

Un saludo

**Comment by ssheduardo** [comment]
El número de pedido es el que tu le pasas, en mi ejemplo yo agregue un time
```
Redsys::setOrder(time());
```
Ahí debes colocar el número de tu pedido respetando el formato que valida redsys, los 4 primeros  deben ser número y con un total de 12
Ejemplo
```
1003FR43224
000123455650
300077890762
```

**Comment by kezern** [comment]
Muchas gracias. 
Al ver la función fecha no había leído bien y  pensaba que era la fecha de la compra


_Sent from my Xiaomi MI 6 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
