### ISSUE TITLE
Código CIP

### ISSUE THREAD

**Issue by kezern** [ssheduardo/redsys-laravel#13]
El desarrollo que estoy haciendo en laravel es para una persona que hasta ahora usaba una plataforma llamada paytpv para hacer los cobros.
Me dice que hasta ahora sólo tenía que meter el número de tarjeta, la fecha de caducidad y el cvv. Me dice que nunca ha tenido que poner el código CIP.
¿Es esto posible? 

Un saludo

_Sent from my Xiaomi MI 6 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by kezern** [comment]
He estado leyendo la documentación de la clase original y veo este párrafo.

Si no queremos que nos muestre ninguna pantalla y directamente realice el pago debemos hacer uso del método setMerchantDirectPayment

$redsys->setMerchantDirectPayment(true);

Creo que eso es lo que necesito.



_Sent from my Xiaomi MI 6 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ssheduardo** [comment]
Ese código CIP depende de cada entidad, en otras te envían un SMS

**Comment by kezern** [comment]
Hola ssheduardo,
Entiendo que también se podría omitir ese CIP mediante el siguiente código


Si no queremos que nos muestre ninguna pantalla y directamente realice el pago debemos hacer uso del método setMerchantDirectPayment

$redsys->setMerchantDirectPayment(true);

¿Correcto?

_Sent from my Xiaomi MI 6 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ssheduardo** [comment]
Cierro issue
