### ISSUE TITLE
Posible Bug Method T

### ISSUE THREAD

**Issue by pwronline** [ssheduardo/redsys-laravel#14]
Buenas Eduardo estaba trabajando con tu repo y me he dado cuenta que si asignas el metodo Redsys::setMethod('T'); no te muestra el pago por iUpay , sin embargo si no asignas ningun metodo si que salen las dos opciones de pago. Para mi esto no tiene sentido ya que el metodo por defecto es el "T" y si se lo asigno yo manualmente el T se comporta como el C solo muestra la opción de pago por tarjeta.

`    /**
     * Payment type
     *
     * @param string $method [T = Pago con Tarjeta + iupay , R = Pago por Transferencia, D = Domiciliacion, C = Sólo Tarjeta (mostrará sólo el formulario para datos de tarjeta)] por defecto es T
     * @throws Exception
     */
    public function setMethod($method='T')
    {
        if(strlen(trim($method)) > 0){
            $this->_setParameters['DS_MERCHANT_PAYMETHODS'] = trim($method);
        }
        else{
            throw new Exception('Add pay method');
        }
    }`

Muchas gracias por tu trabajo.

**Comment by ssheduardo** [comment]
Voy a investigar que pasa, en teoría parece que esta todo bien.

**Comment by ssheduardo** [comment]
He mirado en varias páginas donde el pasar el parámetro T, mostraba tarjeta e iupay pero mirando y probando el código al parecer iupay se muestra por defecto sin pasar dicho parámetro.
Entonces quedaría así:
Si no pasamos el método setMethod, mostrará iupay, pero si llamamos a setMethod pasando tanto vacio, T o C no mostrará iupay.

Debo corregir el texto dentro de la clase y el README

**Comment by pwronline** [comment]
Ok gracias Eduardo!
