### ISSUE TITLE
Renovación de pagos por suscripción

### ISSUE THREAD

**Issue by Kyosfonica** [ssheduardo/redsys-laravel#15]
¿Como se implementaría el sistema de renovación de suscripciones?

Mi idea es que el sistema lo haga todo automáticamente sin intervención del usuario mediante el uso del identificador de tarjeta. ¿Es posible hacer eso con esta clase?

Veo que hay el método executeRedirection pero lanza un javascript que en el lado del servidor no tengo.
¿Hay implementado algún envio de formulario mediante CURL?

Un saludo

**Comment by ssheduardo** [comment]
Hola,
Aún no lo tengo implementado para hacerlo a través de API sin pasar por un formulario.
Esta semana a lo mejor si me da tiempo lo implemento.

**Comment by Kyosfonica** [comment]
Pero o que comento es posible, no?

Osea, primer pago lo hace el usuario, el resto los hace solo el sistema.

**Comment by ssheduardo** [comment]
Si eso puedes preguntar al banco y ver si ellos lo hacen cada mes o tienes que ser tú quien lance cada mes dicho cobro.

**Comment by Kyosfonica** [comment]
He contactado con el banco y soy yo quien debe lanzar el cobro diferido cuando sea necesario usando los datos de DS_Merchant_Identifier para saber a que tarjeta hay que mandar el cobro

**Comment by ssheduardo** [comment]
Genial entonces, si logras hacerlo y compartirlo para agregarlo al README

**Comment by danielcharrua** [comment]
Al final existe la opción de pagos por suscripción en este paquete? Sería interesante 💪

**Comment by ssheduardo** [comment]
El paquete cuenta con casi todos los métodos, solo hay que ver las pautas que marca el banco y lanzarlo.
lamentablemente "REDSYS" no es capaz de darme un usuario de pruebas para poder investigar más.
Me solicitan el contratar el servicio y OJO, previo estudio para ver si me lo dan.
Les he escrito comentando la ayuda que presto a la comunidad y lo único que me han dicho.
"Me puede dar el FUC de la empresa para darle soporte"-

**Comment by danielcharrua** [comment]
@ssheduardo que lástima ya que estaría buenísimo agregarle la parte de suscripción a la documentación.

He visto que tienes otro paquete https://github.com/ssheduardo/sermepa donde hablas del pago por referencia en la documentación, imagino que se puede lograr lo mismo con el paquete de Laravel, es correcto?

Voy a ver si me puedo hacer un TPV y probar la operativa. ¿A ti te lo han negado entonces?

**Comment by Kyosfonica** [comment]
Perdon por volver tantos años después. El cliente con el que desarrollé esto al final desechó las suscripciones. Al no necesitar esa programación, no compartí esa implementación aquí ya que nunca la llegué a realizar.

**Comment by ssheduardo** [comment]
> @ssheduardo que lástima ya que estaría buenísimo agregarle la parte de suscripción a la documentación.
> 
> He visto que tienes otro paquete https://github.com/ssheduardo/sermepa donde hablas del pago por referencia en la documentación, imagino que se puede lograr lo mismo con el paquete de Laravel, es correcto?
> 
> Voy a ver si me puedo hacer un TPV y probar la operativa. ¿A ti te lo han negado entonces?

Efectivamente es una pena que REDSYS no apoye los desarrollo de este tipo, la verdad que cuanto más fácil sea el integrar esto mejor, no te quedas frustrado.
Efectivamente los métodos de la clase base sermepa (redsys) se pueden usar con la de Laravel, hereda todas las clases.
Lo que tenía ahí es lo que fui mirando en la documentación y cuando se podía probar sin restricciones.
La última vez tuve que integrar redsys usando Insite y tengo código para compartir pero tengo que agregar nuevos métodos para que sea más fácil.
El problema "NO TENGO UN FUC" para que me puedan habilitar el entorno de Desarrollo.

**Comment by ssheduardo** [comment]
> Perdon por volver tantos años después. El cliente con el que desarrollé esto al final desechó las suscripciones. Al no necesitar esa programación, no compartí esa implementación aquí ya que nunca la llegué a realizar.

Hubiera venido de perlas el poder ver esos ejemplos probarlo e integrarlo en la documentación.

**Comment by danielcharrua** [comment]
Yo mande correo a los de Redsys y a mi banco a ver si consigo un usuario para probar. Os mantengo al tanto 💪

**Comment by ssheduardo** [comment]
> Yo mande correo a los de Redsys y a mi banco a ver si consigo un usuario para probar. Os mantengo al tanto muscle

Estaría genial la verdad, se podría usar para hacer muchas pruebas, agregar lo del Insite que cuando pillas como va con un par de ejemplo lo tienes ya.
