### ISSUE TITLE
Monedas

### ISSUE THREAD

**Issue by angallego** [ssheduardo/redsys-laravel#16]
Buenas, 

¿A que se debe la validación para solo esos 4 determinados tipos de moneda?
Quiero decir, necesito implementar una moneda que no es ninguna de las cuatro validadas (Euros, Dólares, Libras ni Yenes).

vendor\ssheduardo\redsys-laravel\src\Tpv.php@setCurrency

**Comment by ssheduardo** [comment]
De la documentación de Redsys, no se si habrán implementado más monedas.
![image](https://user-images.githubusercontent.com/1160138/38310289-72c411e2-381c-11e8-8e31-71f024c02c48.png)

**Comment by angallego** [comment]
En realidad se trata de 4 ejemplos de monedas, pero no está limitado únicamente a esas 4. Se trata del código de monedas **ISO-4217**. La única validación que tiene es que sea **numérico** de **longitud máximo de 4**.

https://canales.redsys.es/canales/ayuda/documentacion/Manual%20integracion%20para%20conexion%20por%20Redireccion.pdf

![image](https://user-images.githubusercontent.com/23311807/38311743-3a7760ba-3820-11e8-9e44-0477a51968c1.png)

**Comment by ssheduardo** [comment]
Toda la razón lo acabo de ver, va tocar hacer un hotfix

**Comment by ssheduardo** [comment]
Aunque permite 4 digitos, he visto la tabla estándar y hasta ahora solo usan 3 dígitos, creo que lo dejare con 3.
https://es.iban.com/currency-codes.html

**Comment by ssheduardo** [comment]
Acabo de subir un hotfix, mira si te va.

**Comment by vtscarlos** [comment]
Aprovechando los hotfix si me quitas  && is_numeric(substr($order,0,4)) de la linea 103 de Tpv.php me haces padre.

Ya que no puedo actualizar porque mis números de pedido que envío a redsys no comienzan por números

**Comment by ssheduardo** [comment]
¿Cómo te deja enviar pedidos que no empiezan por número?

![image](https://user-images.githubusercontent.com/1160138/38320120-fa8a1560-3833-11e8-8976-e44d3311ac0d.png)

**Comment by angallego** [comment]
Es curioso! Pero de hecho, a mi también me funciona siendo 4 letras los los primeros caracteres. 
¿Podrías hacer algo para yo también sincronizarme a la última versión del _package_?

**Comment by ssheduardo** [comment]
¿Cómo así?
Con hacer un update del repositorio obtendrías los últimos cambios.

**Comment by angallego** [comment]
Yo estoy en la v1.1.2 y no puedo actualizar a tu última versión por esta validación que se hace en _setOrder()_ ya que mi [DS_MERCHANT_ORDER] empieza por letras...

**Comment by ssheduardo** [comment]
Vaya, el problema que la validación no puedo cambiarlo por que puede afectar a muchos y dado que la documentación nos indica que la numeración debe ser tal cual aunque según comentas puede empezar con letras.
Lo que puede hacer es un fork y cambiar la validación de setOrder.
