### ISSUE TITLE
mcrypt_encrypt is deprecated

### ISSUE THREAD

**Issue by carlituxman** [ssheduardo/redsys-laravel#17]
With php 7.1 we have error mcrypt_encrypt is deprecated

**Comment by ssheduardo** [comment]
https://github.com/ssheduardo/redsys-laravel/blob/master/CHANGELOG.md#112-2017-01-27

**Comment by carlituxman** [comment]
I have problems now with this:ç
if(strlen($order) > 0 && strlen($order) <= 12 && is_numeric(substr($order,0,4)) ){
at Tpv.php line 103
with: is_numeric(substr($order,0,4)

why this? my order is: like B1144-89731

why should be numeric substr($order,0,4) ?

**Comment by ssheduardo** [comment]
The official documentation.

![image](https://user-images.githubusercontent.com/1160138/40966787-b8f0cad2-68b1-11e8-98cd-f5692985e2bd.png)

**Comment by carlituxman** [comment]
aaah ok. thanks!!
