### ISSUE TITLE
SIS0463 - No existe método de pago válido para su tarjeta

### ISSUE THREAD

**Issue by CristianFunky** [ssheduardo/redsys-laravel#18]
Llevo varios días con quebraderos de cabeza por este error que me aparece tras intentar pagar con tarjeta desde la pasarela de pago. He probado a poner setMethod('C') y setMethod('T'), para ver si era porque me estaba detectando algún tipo de pago diferente, pero nada de nada.
La verdad es que estoy un poco perdido con este error (que con los datos de prueba globales y con la tarjeta de prueba de redsys no me salía) y que ahora en producción me aparece. 
¿Alguna idea?

**Comment by DevDyanamic** [comment]
Hola, resolviste el problema, tengo el mismo problemas y no doy con la causa, me podrias decir como resolviste el problema

**Comment by ssheduardo** [comment]
Estamos hablando de un problema reportado en el 2018, ya ha pasado mucho desde entonces.
¿Qué problemas tienes exactamente?
Trata de aportar más datos, capturas de pantalla, algo de código, etc.
