### ISSUE TITLE
Class tpv does not exist

### ISSUE THREAD

**Issue by gonself** [ssheduardo/redsys-laravel#19]
Buenas!
Excelente paquete, ya lo use en su día sin problemas, pero en un nuevo proyecto, en Laravel 5.5 tras instalarlo como se comenta en el readme me da este error... no entiendo porque... podéis indicarme por donde pueden ir los tiros?

Gracias de antemano.
Un saludo.

Edito: He tenido que incluir el provider a mano en app.php, a pesar de ser una instalación Laravel 5.5, por si a alguien le ocurre

**Comment by ssheduardo** [comment]
Que raro, esta preparado para dicha versión.
Seguiste el README tal cual con Laravel 5.5 y salto ese error?

**Comment by gonself** [comment]
Si es raro... añadí el require manualmente a composer.json, luego composer update y composer dump-autoload...

La instalación de Laravel está un poco modificada no obstante no me ha ocurrido con ningún otro package... Luego con tiempo revisare si todos los autoloads están bien generados... 

Gracias

**Comment by ssheduardo** [comment]
Si saco hueco luego lo pruebo desde 0

**Comment by ssheduardo** [comment]
Llegaste a resolverlo @gonself ?

**Comment by gonself** [comment]
Disculpa @ssheduardo,

Lo resolví metiendo las referencias a mano, no obstante como te comentaba la instalación estaba modificada en cuanto a directorios y no descarto que sea cosa mía...

muchas gracias!

**Comment by danielap82albarregas** [comment]
> 
> 
> Disculpa @ssheduardo,
> 
> Lo resolví metiendo las referencias a mano, no obstante como te comentaba la instalación estaba modificada en cuanto a directorios y no descarto que sea cosa mía...
> 
> muchas gracias!

Buenas, os he leido porque me está pasando lo mismo, ¿Me podrías decir como metiste las referencias a mano?, un saludo y gracias.

**Comment by ssheduardo** [comment]
Sería bueno detallar este punto.

**Comment by danielap82albarregas** [comment]
Disculpad, tras re repasar todo de nuevo, en el servidor de producción, por algún motivo no estaba incluido en config/app.php el Application Service Provider, por lo que ya no tengo el problema.

**Comment by gonself** [comment]
Buenas,
En su día tuve que inclur el service en app.php... pero de esto hace mucho tiempo, tendriamos que probar actualmente como está el tema...
Saludos.
