### ISSUE TITLE
Tengo este error

### ISSUE THREAD

**Issue by rifayman** [ssheduardo/redsys-laravel#2]
Hola eduardo

me sale este error y my key ese
ErrorException in Tpv.php line 557:
mcrypt_encrypt(): Key of size 0 not supported by this algorithm. Only keys of size 24 supported

'key' => env('APP_KEY', 'UQoXVI0WTXl0CxTKnxo0r5VfEvZAkw3i'),

    'cipher' => 'AES-256-CBC',

no se porque??

un saludo

**Comment by ssheduardo** [comment]
Creo que puede ser por la versión de PHP, el ejemplo te funciona?

**Comment by rifayman** [comment]
tengo PHP Version 5.6.15



2016-04-18 13:25 GMT+02:00 Eduardo <notifications@github.com>:

> Creo que puede ser por la versión de PHP, el ejemplo te funciona?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ssheduardo/redsys-laravel/issues/2#issuecomment-211337247>
>



-- 
Fikri Abouelyazid

**Comment by ssheduardo** [comment]
Prueba con el ejemplo que funciona sin problemas para ver que puede ser.

**Comment by rifayman** [comment]
he cambiado este $key = config('redsys.key'); con  $key =
'sq7HjrUOBfKmC576ILgskD5srU870gJ7';

y me sale un button send entocies funciona??

un saludo

On 18 April 2016 at 13:34, Eduardo <notifications@github.com> wrote:

> Prueba con el ejemplo que funciona sin problemas para ver que puede ser.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ssheduardo/redsys-laravel/issues/2#issuecomment-211340819>
>



-- 
Fikri Abouelyazid

**Comment by ssheduardo** [comment]
Si esta funcionando, debe ser tu key entonces.

**Comment by rifayman** [comment]
Si gracias un abrazo :)

On 18 April 2016 at 13:42, Eduardo <notifications@github.com> wrote:

> Si esta funcionando, debe ser tu key entonces.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ssheduardo/redsys-laravel/issues/2#issuecomment-211342271>
>



-- 
Fikri Abouelyazid

**Comment by rifayman** [comment]
Hola eduardo

Que tal todo??

tengo un duda sobre redsys puedo mostrar un mensage en redsysy SIN DAR
CLCIK en finalizar el pago


un abrazo

On 18 April 2016 at 13:44, Eduardo <notifications@github.com> wrote:

> Closed #2 <https://github.com/ssheduardo/redsys-laravel/issues/2>.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ssheduardo/redsys-laravel/issues/2#event-631167208>
>



-- 
Fikri Abouelyazid

**Comment by ssheduardo** [comment]
Como así?

**Comment by rifayman** [comment]
te enviado un captura


mostrar un mensage en redsysy SIN DAR CLCIK en finalizar el pago

On 12 July 2016 at 11:34, Eduardo <notifications@github.com> wrote:

> Como así?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ssheduardo/redsys-laravel/issues/2#issuecomment-231988174>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AD8Z2hzrfTEh1rDOGzXxFp2CTLAXa-ayks5qU1-tgaJpZM4IJnct>
> .
>



-- 
Fikri Abouelyazid

**Comment by ssheduardo** [comment]
Esperando captura
