### ISSUE TITLE
Redirección automática a URL_OK si el pago es correcto

### ISSUE THREAD

**Issue by BlackCoronel** [ssheduardo/redsys-laravel#23]
Me gustaría saber como puedo hacer para que si el pago es correcto, automáticamente desde la página de Redsys me redirija a mi URL_OK por defecto. Ya que hora mismo, solo lo hace si los clientes le dan al botón de continuar.

![image](https://user-images.githubusercontent.com/22600233/54748083-ec39c300-4bd0-11e9-82e5-434ac919cadb.png)

Perdonad mi ignorancia, pero nunca había usado antes este módulo de Redsys y ante todo gracias a los desarrolladores por hacerlo posible.

Gracias de antemano.

**Comment by ssheduardo** [comment]
Hola @BlackCoronel puedes ver más ejemplos en la clase base https://github.com/ssheduardo/sermepa, creo recordar qu se podía hacer, tendría que verlo.

**Comment by BlackCoronel** [comment]
@ssheduardo Básicamente cuando le das a continuar se ejecuta la función comprobar(), que confirma si ha pagado o no.  Si no se puede redireccionar automáticamente... ¿ Como le paso los parámetros de que todo esta bien a mi función?

`
public function comprobar(Request $request)

    {

        try{

            $key = config('redsys.key');

            $parameters = Redsys::getMerchantParameters($request->input('Ds_MerchantParameters'));

            $DsResponse = $parameters["Ds_Response"];

            $DsResponse += 0;

            if (Redsys::check($key, $request->input()) && $DsResponse <=99) {
               DB::table('pagos')->where('referencia',$parameters['Ds_Order'])->update([
                   'respuesta' => $parameters['Ds_Order'],
               ]);
               // Vista de todo OK.
            } else {
                // Vista confirmación inscripción a falta de pago.
            }

        } catch (\Sermepa\Tpv\TpvException $e) {

            echo $e->getMessage();

        }

    }
`
Gracias y un saludo.

**Comment by ssheduardo** [comment]
No estoy muy seguro pero creo que se puede hacer, pasando los datos de la tarjeta, no estoy seguro al 100%, podrias preguntar al banco para que te de más información

**Comment by oriolrg** [comment]
Yo tambien estoy con el problema que no me ejecuta comprobar, tengo la route assignada en notificacion, que apunta a la funcion, pero no me actualiza la base de datos. La funcion de actualizacion esta testeada y funciona bien. Hay alguna forma de obtener el log para ver si me da algun error?

**Comment by ssheduardo** [comment]
Una cosa, prueba a solo grabar un el log y así compruebas si efectivamente el banco esta llamando a tu url, recuerda que la url no debe ser de tu local, dado que el banco nunca va a encontrar localhost/ruta/algo.php

**Comment by BlackCoronel** [comment]
Me puse en contacto con el soporte de Redsys y me comentaron que para poder hacer una redirección automática, cuando el pago estaba OK, había que configurarlo desde el panel de Redsys.

**Comment by mavbcn** [comment]
Hola!
Es posible que cuando el usuario ha pagado, llevarlo a la misma sección de la web en la que se encontraba cuando realizo el pago?
como deberia hacerlo? 
 
Muchas gracias
un saludo
