### ISSUE TITLE
QUESTION: Redireccion REDSYS_URL_NOTIFICATION 

### ISSUE THREAD

**Issue by oriolrg** [ssheduardo/redsys-laravel#24]
QUESTION : en laravel, hay alguna forma para enviar un token para corroborar que la modificacion ejercida por esta redireccion no es echa por alguien que no sea el bancal?

**Comment by ssheduardo** [comment]
Creo que para ello se usa la notificación, el banco realiza de forma transparente dicha llamada para que podáis gestionar x cosas en vuestro sistema.
