### ISSUE TITLE
Recurring Payments

### ISSUE THREAD

**Issue by vanandmkrtchyan** [ssheduardo/redsys-laravel#25]
does this package support recurring payments?

**Comment by ssheduardo** [comment]
Hi @vanandmkrtchyan,
Please see https://github.com/ssheduardo/sermepa#pago-con-referencia

**Comment by vanandmkrtchyan** [comment]
> Hi @vanandmkrtchyan,
> Please see https://github.com/ssheduardo/sermepa#pago-con-referencia

Thanks. Will check and respond asap.
