### ISSUE TITLE
URLOK tras el pago y redirección a web

### ISSUE THREAD

**Issue by mavbcn** [ssheduardo/redsys-laravel#28]
Hola!
Primero de todo muchas gracias por la dedicación a desarrollar este paquete, sin duda una gran ayuda. Muchas gracias!!

Tengo un pequeño problema/duda que no se muy bien como resolver:

Quiero que una vez hecho el pago., el usuario vuelva a la misma sección de la web de donde inicio el pago, ya que estoy desarrollando un pequeño proyecto en el que se pueden comprar diferentes tipos de servicios y cada uno de ellos se compra desde una sección distinta. 

Me gustaría que una vez que el usuario ha hecho el pago, y este es correcto, se le redirija a la misma sección desde donde lo inicio. 
como podría hacer esto, ya que tengo entendido que la url de notificación la hace de forma transparente el banco.
 
muchas gracias por la ayuda
un saludo

**Comment by ssheduardo** [comment]
Hola @mavbcn,
Ahí me has pillado, no se si en el url_ok puedes pasar parámetro, tendrías que probar pasando algo así:
```
http://url/ok.php?back=juguetes
http://url/ok.php?back=ropa

```
Y así tu recoger dicho valor y según sea el caso hagas la redirección, pero tienes que ver si realmente al pasar dicho dicho dato en la url ok, te retorna los parámetros.

Otra cosa sería crear alguna session o algo así que al llamar a la url ok, detecto si esta creado la variable de sesion y según sea como lo creaste la variable de sesión te realice la redirección.
