### ISSUE TITLE
Falta posibilidad de establecer DS_MERCHANT_CONSUMERLANGUAGE

### ISSUE THREAD

**Issue by markxxv** [ssheduardo/redsys-laravel#29]
Por lo visto en ese paquete no es posible establecer el parámetro DS_MERCHANT_CONSUMERLANGUAGE.

Si hay algún modo sin hacer fork establecerlo?

**Comment by ssheduardo** [comment]
Tendría que implementarlo y subir una nueva versión.

**Comment by soulcodex** [comment]
También puedes importar directamente la clase Tpv de sermepa y llamar al metodo que hace set de este campo :)

**Comment by ssheduardo** [comment]
En la clase base acabo de implementar el método setParameters para que puedas enviar más parámetros.
https://github.com/ssheduardo/sermepa/blob/master/CHANGELOG.md
