### ISSUE TITLE
Redireccionar el formulario al banco automáticamente

### ISSUE THREAD

**Issue by ncarreno** [ssheduardo/redsys-laravel#3]
Sería muy útil que en el formulario que se genera este se enviara sin necesidad de pulsar el botón submit. He hecho un cambio en el archivo Tpv.php quitando el botón submit y añadiendo esta línea:
`<script type="text/javascript">document.getElementById("' . $this->_setIdForm . '").submit();</script>`

**Comment by ssheduardo** [comment]
Hola @ncarreno,
Existe un método llamado **executeRedirection** para dicha labor.
