### ISSUE TITLE
URL en entorno produccion

### ISSUE THREAD

**Issue by oriolrg** [ssheduardo/redsys-laravel#30]
Me encuentro que tenco todo configurado para produccion pero redsys sigue utilizando la url de pruevas. Como modifico esta url? El REDSYS_ENVIROMENT ya esta en 'live'

Muchas gracias

**Comment by oriolrg** [comment]
Solucionado, estava modificando el redsys config y realmente usava el .env.

Muchas gracias igualmente.

**Comment by ssheduardo** [comment]
De nada
