### ISSUE TITLE
Error installing in 5.8

### ISSUE THREAD

**Issue by luismabenitez** [ssheduardo/redsys-laravel#32]
Having this problem: 

./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package ssheduardo/redsys could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json to its original content.

**Comment by ssheduardo** [comment]
I did install a new version of Laravel 5.8 and install the package redsys-laravel without problem.

![image](https://user-images.githubusercontent.com/1160138/64863629-9c92fc00-d635-11e9-96fa-348138160e63.png)

Testing in MacOs with Valet:
- Php 7.1.30
- Mysql 5.7.27
