### ISSUE TITLE
Problema con URL_NOTIFICATION

### ISSUE THREAD

**Issue by ogonzalezf** [ssheduardo/redsys-laravel#33]
Hola estoy intentando integrar su paquete a una solucion  que tengo pero a la hora de realizar el pago, va bien para la URL_OK, pero la URL_NOTIFICATION, no es visitada nunca, es decir no tengo respuesta en esa url. Alguna sugerencia de que puediera estar pasando

**Comment by ssheduardo** [comment]
Recuerda que la url de notificación tiene que ser válida, no vale un localhost.
