### ISSUE TITLE
Target class [tpv] does not exist. 

### ISSUE THREAD

**Issue by MiquelRoan** [ssheduardo/redsys-laravel#34]
Hola Eduardo,
Estoy en Laravel 6.x.x y tengo el error: Target class [tpv] does not exist.
He seguido el README a rajatabla.
La cuestión es que en el entorno de desarrollo local, funciona bien (WAMP).
Pero al subirlo a producción obtengo dicho error. 
Imagino que tendremos diferentes configuraciones de Apache, si es que IONOS usa Apache, que no lo puedo asegurar en este momento.
Por otro lado, muchísimas gracias por el módulo.

**Comment by ssheduardo** [comment]
Que raro que en local te vaya bien y no en PRO.
Y el resto de paquetes te funciona??

**Comment by MiquelRoan** [comment]
sí, el resto de paquetes funciona sin problemas.
¿Hay alguna manera de ver si estoy importando mal la clase Redsys?
Tengo `use Ssheduardo\Redsys\Facades\Redsys;`

**Comment by ssheduardo** [comment]
Si, esta bien en principio, lo que no me cuadra es que en local si funciona.
Tendría que montar un laravel 6 y probarlo en algún servidor.
