### ISSUE TITLE
Soporte para Laravel >= 6

### ISSUE THREAD

**Issue by nlucia** [ssheduardo/redsys-laravel#35]
La versión 1.4.0 necesita Laravel 6, creo que podría ampliarse también a versiones superiores

**Comment by ssheduardo** [comment]
Hola @nlucia , te ha dado error al usarlo con L6 o estas comentando que podría servir para las siguientes versiones de Laravel?

**Comment by nlucia** [comment]
Perdona @ssheduardo, quería decir lo segundo

**Comment by ssheduardo** [comment]
Ah vale puede ser para la versión 7, lo anoto para luego ponerme.

**Comment by nlucia** [comment]
Gracias, perdona por explicarme regular. Creo que con cambiar el requerimiento de laravel de '^6.0' a '>=6.0'  valdría.

**Comment by nlucia** [comment]
Te confirmo que he probado con laravel 7.5.2 y funciona. Un saludo.

**Comment by ssheduardo** [comment]
Genial lucia, por falta de tiempo no me he puesto a probarlo, solo has agregado la librería en la 7.5,2 y te ha funcionado, sies así para solo actualizar el README.

**Comment by nlucia** [comment]
Lo único que hay que cambiar es la versión requerida de laravel en composer.json, de '^6.0' a '^6.0|^7.0' o '>=6.0'.
Gracias y un saludo,

**Comment by ssheduardo** [comment]
Guay, mañana hago el update

**Comment by ssheduardo** [comment]
Bueno al final como es poco lo acabo de hacer ahora, lo podéis probar?

**Comment by nlucia** [comment]
Hola Eduardo, funciona correctamente.
Gracias y un saludo.
