### ISSUE TITLE
Parámetros de url_notification en url_ok??

### ISSUE THREAD

**Issue by fmenacho** [ssheduardo/redsys-laravel#36]
Buenas ssheduardo, según comentas, la url_ok no tiene información del pago, pero según la documentación de Redsys, dice que opcionalmente se pueden incluir los mismos campos que vienen en la url_notification. ¿Hay alguna manera de hacer esto a través de tu clase?

Esto es lo que dice la documentación de Redsys.

2.3 Retorno del control de la navegación del titular
En el paso 4 del flujo el TPV Virtual devuelve al comercio el control de la
navegación del titular. De esta forma el comercio puede completar el flujo del pago
manteniendo una secuencia de navegación natural para el cliente/comprador.
Opcionalmente el TPV Virtual puede incluir los mismos campos de la notificación
on-line.

Un saludo y gracias.

**Comment by ssheduardo** [comment]
Pero la url_ok recibe la información directamente del banco y la clase lo procesa, lo que no se o no he visto es como decirle a redsys que te envíe en la url_ok lo que tiene la url_notificación, de todas maneras estas exponiendo datos sensibles de la utl_notificación que cualquiera podrá verlo.
Qué es exactamente lo que necesitas?

**Comment by fmenacho** [comment]
Lo que necesitaría es identificar que elemento ha sido el que he pegado, pero desde la url_ok, porque desde la de notificación, puedo saberlo por ejemplo, con el Ds_Order, que es el mismo antes de generar el formulario, y cuando responde después del pago en la url_notification. Pero a través de la url_ok no puedo saber que ha sido capaz de relacionar la respuesta con el elemento que haya pagado el cliente. Necesitaría que algún atributo se se repitiera antes me mandar al cliente a redsys, y después al devolver la url_ok, y que fuera distinto para cada pago realizado.
