### ISSUE TITLE
Laravel 7

### ISSUE THREAD

**Issue by Redorash** [ssheduardo/redsys-laravel#37]
Hola! Primero de todo gracias por el aprote. ¿Puedes revisar si es compatible con la última versión de Laravel y hacer commit para poder instalar en laravel 7? No deja instalar.

**Comment by ssheduardo** [comment]
Mañana realizo el update.

**Comment by ssheduardo** [comment]
Lo acabo de subir ahora, puedes probarlo por favor.

**Comment by Redorash** [comment]
Pese a que has sido muy rápido, ya me había creado un "Fork" del repo y lo he probado cambiando el require del composer. Parece que todo bien con laravel 7. Gracias por mantener. Un saludo.
