### ISSUE TITLE
la url_notification nunca se ejecuta

### ISSUE THREAD

**Issue by francescverdu** [ssheduardo/redsys-laravel#39]
Estoy probando el módulo laravel, la url_ok y la url_ko funcionan correctamente pero la url_notification no se ejecuta nunca. ¿Cuándo se supone que deberia llamarse? ¿Es posible que por estar en entorno test no sea llamada?
En el archivo config/redsys.php tengo:

    'url_notification'   => url('/').'/notif',
    'url_ok'             => url('/').'/ok',
    'url_ko'             => url('/').'/ko',

para que se llamen la rutas de laravel: 

    Route::post('/notif','RedsysController@notif);');   
    Route::get('/ok','RedsysController@ok);');
    Route::get('/ko','RedsysController@ko);');

la ok y la ko se ejecutan al finalizar la operativa, mientras que la notif no se ejecuta nunca.

**Comment by ssheduardo** [comment]
Mira esto, https://github.com/ssheduardo/redsys-laravel/issues/38
Puede ser por el middleware que trae Laravel y que te solicita el Token

**Comment by francescverdu** [comment]
Toda la razón, es eso.

Mil gracias!!!


Francesc Verdú i Carbó
netbynet Consulting de Sistemes, S.L.
francesc@netbynet.net<mailto:francesc@netbynet.net>

Aquest missatge electrònic està dirigit únicament a le(s) direcció(ns) indicades anteriorment; el caràcter confidencial, personal i intransferible del mateix està protegit legalment. Qualsevol revelació, ús o reenviament no autoritzat, complet o en part, està prohibit. Si ha rebut aquest missatge per equivocació, notifiqui-ho inmediatament a la persona que ho ha enviat i esborri el missatge original juntament amb els seus fitxers annexos sense llegir-lo ni gravar-lo, total o parcialment. Gràcies per la seva col·laboració.

Este mensaje electrónico está dirigido únicamente a la (s) dirección (es) indicadas anteriormente, el carácter confidencial, personal e intransferible del mismo está protegido legalmente. Cualquier revelación, uso o reenvío no autorizado, completo o en parte, está prohibido. Si ha recibido este mensaje por equivocación, notifíquelo inmediatamente a la persona que lo ha enviado y borre el mensaje original junto con sus ficheros anexos sin leerlo ni grabarlo, total o parcialmente. Gracias por su colaboración.



De: Eduardo <notifications@github.com>
Enviado el: dimecres, 22 d’abril de 2020 18:14
Para: ssheduardo/redsys-laravel <redsys-laravel@noreply.github.com>
CC: Francesc Verdú <francesc@netbynet.net>; Author <author@noreply.github.com>
Asunto: Re: [ssheduardo/redsys-laravel] la url_notification nunca se ejecuta (#39)


Mira esto, #38<https://github.com/ssheduardo/redsys-laravel/issues/38>
Puede ser por el middleware que trae Laravel y que te solicita el Token

**Comment by mazcvei** [comment]
¿Como se solucionaría entonces?

**Comment by francescverdu** [comment]
en \App\Http\Middleware\VerifyCsrfToken.php  pones las rutas excluidas de csrf en la tabla $except
