### ISSUE TITLE
Imposible instalar Laravel 5.3

### ISSUE THREAD

**Issue by Krato** [ssheduardo/redsys-laravel#4]
Hola, no hay manera de instalarlo en Laravel 5.3.

Había pensando en hacer un fork, pero prefiero preguntar primero.

Composer muestra este error:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package ssheduardo/redsys could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
```

He probado también a añadir `dev-master` a composer pero tampoco.

Muchas gracias.

**Comment by ssheduardo** [comment]
Lo reviso a ver que ha pasado

**Comment by ssheduardo** [comment]
@Krato ya esta solucionado

**Comment by Krato** [comment]
Muchas gracias por agregar la compatibilidad a laravel 5.3. SIn embargo sigue dando el mismo error.

¿Tal vez quitando el `"minimum-stability": "stable"`?

**Comment by ssheduardo** [comment]
Así, lo probé en un proyecto con Laravel 5.3 y no da error, puedes probarlo en una instalación limpia.

**Comment by Krato** [comment]
Perfecto. Ahora sí. Muchas gracias 👯
