### ISSUE TITLE
Class tpv does not exist en Laravel 5.4

### ISSUE THREAD

**Issue by angelprietofi** [ssheduardo/redsys-laravel#41]
Buenos días Eduardo,

Primeramente, agradecerte tu gran esfuerzo y dedicación para desarrollar los sistemas de Redsys. Estoy tratando de instalarlo en laravel **5.4.36** y tengo el siguiente problema:

> Class tpv does not exist 

EN composer.json:
`"ssheduardo/redsys-laravel": "~1.1.0",`

En config\app.php:
En providers:
` Ssheduardo\Redsys\RedsysServiceProvider::class,`
En aliases:
`'Redsys'    => Ssheduardo\Redsys\Facades\Redsys::class,`
 
Al ejecutar el siguiente codigo no me genera el archivo de configuración de redsys. pero lo he creado manualmente:
`php artisan vendor:publish --provider="Ssheduardo\Redsys\RedsysServiceProvider"`

En el controlador creado:
```
use Illuminate\Http\Request;
use App\Http\Requests;
use App\Http\Controllers\Controller;
use Ssheduardo\Redsys\Facades\Redsys;
```

**Comment by ssheduardo** [comment]
Prueba con la 1.1.3

**Comment by angelprietofi** [comment]
En composer.lock ahora:
```
"name": "ssheduardo/redsys-laravel",
            "version": "1.1.3",
            "source": {
                "type": "git",
                "url": "https://github.com/ssheduardo/redsys-laravel.git",
```

No obstante, cuanto ejecuto tampoco se me abre el archivo de configuración. Lo cree yo manualmente, pero lo borro temporalmente para probar que lo ejecute

`php artisan vendor:publish --provider="Ssheduardo\Redsys\RedsysServiceProvider"`

Un saludo,

**Comment by ssheduardo** [comment]
Tendría que bajarme un laravel 5.4.36 para hacer la prueba.

**Comment by angelprietofi** [comment]
¿Es posible que en la instalación haya hecho algo mal? He tratado de seguir todos los pasos de forma correcta. ¿Alguna solución parcial?

**Comment by ssheduardo** [comment]
Estoy configurando un entorno con laravel 5.4

**Comment by ssheduardo** [comment]
Acabo de realizar una instalación limpia y ejecutar el archivo que crea el archivo de configuración sin problema.

![image](https://user-images.githubusercontent.com/1160138/82129864-58f52100-97c6-11ea-8abb-3c573cf51bbb.png)


![image](https://user-images.githubusercontent.com/1160138/82129834-1df2ed80-97c6-11ea-8431-aed26b1350c8.png)

![image](https://user-images.githubusercontent.com/1160138/82129850-39f68f00-97c6-11ea-9449-e9038221165f.png)

![image](https://user-images.githubusercontent.com/1160138/82129902-b8533100-97c6-11ea-993c-6968f7348241.png)

**Comment by angelprietofi** [comment]
Muchas gracias!

¿ALguna idea de qué puedo estar haciendo mal?


Ángel Prieto Fidalgo


************ AVISO LEGAL ***********
Este mensaje y los archivos que en su caso lleve adjuntos son privados y
confidenciales y se dirigen exclusivamente a su destinatario. Por ello, se
informa a quien lo reciba por error que la información contenida en el
mismo es
reservada y su utilización, copia o distribución está prohibida, por lo que
en
tal caso le rogamos que nos lo comunique por esta misma vía y proceda a
borrarlo
de inmediato.

**Comment by ssheduardo** [comment]
Ni idea la  verdad, he realizado una instalación limpia.
