### ISSUE TITLE
Error en la url de notificación

### ISSUE THREAD

**Issue by sbellver** [ssheduardo/redsys-laravel#42]
Hola.

Estamos teniendo problemas con la url de notificación, que es donde cambiamos el estado a pagado del pedido.

En algunas transacciones funciona correctamente, pero en otras no pasa por la URL de notificación.

En el `if (Redsys::check($key, $request->input()) && $DsResponse <=99)` tenemos el cambio de estado a Pagado.

En el else tenemos el cambio de estado a Rechazado.

Pues tenemos muchas transacciones "Sin finalizar" pero en Redsys nos figurar como pagadas. Si pasan por la url de notificación, deberían cambiar el estado a uno u otro (Pagado o Rechazado), pero nunca se debería quedar "Sin finalizar"

** Update; en el else teníamos:
`} else if(Redsys::check($key, $request->input()) && $DsResponse > 99){`

Por lo que a veces no entraba y no cambiaba el estado.

Aún quitando esto, ahora tendremos en Rechazado (el else) pagos que en Redsys nos figuran como correctos.

¿Es factible quitar el Redsys::check($key, $request->input()) del if principal? En principio si el DsResponse es correcto, debería bastar.

**Comment by ssheduardo** [comment]
Hola,
Si te das cuenta el método check comprueba el signature
https://github.com/ssheduardo/sermepa/blob/master/src/Sermepa/Tpv/Tpv.php#L748

Por eso el ese if para ver que coincide el signature, luego el DsResponse que en principio > 99 es como válido, lo que puedes hacer es para probar poner 2 if, uno con el Redsys::check para comprobar el signature y luego el DsResponse > 99 y ver por donde pasa y hacer un debug para ver el fallo, de todas maneras quien llama y pasa los parámetro a la url de notificación es Redsys.

**Comment by sbellver** [comment]
Gracias Eduardo.

La duda era si se puede quitar la validación de la signatura, pero entiendo que es importante XD

Creo que teníamos un error en las rutas asi que no parece que haya problema en el componente; pero no entiendo como algunos si cambian de estado y otros no, si la ruta es incorrecta... En fin, hemos corregido lo que hemos visto, confío en que se solucione con esto.

Gracias
