### ISSUE TITLE
Notificar cuando el usuario sale del proceso de pago

### ISSUE THREAD

**Issue by alberto1199** [ssheduardo/redsys-laravel#43]
Hola Eduardo,
Primero de todo agradecerte tu esfuerzo en ofrecernos la posibilidad de pagar por redsys con Laravel.

Estoy intentando hacer que cuando el usuario se salga del proceso de pago le llegue una notificación vía email. Pero no estoy del todo seguro si eso se puede hacer actualmente.

Gracias de antemano.

**Comment by ssheduardo** [comment]
Qué es exactamente lo que quieres hacer¿?

**Comment by alberto1199** [comment]
Si el usuario entra a hacer el pago por redsys, pero por algún motivo cierra la pagina del pago de redsys, no se si hay algún método para detectar el cierre del redsys y enviar un correo como que no ha terminado el pago, para reanudar tu compra pincha aqui.

**Comment by ssheduardo** [comment]
Eso creo que ya dependerá de la parte del banco, recuerda que al hacer el pago, esta fuera de tu dominio y entra en acción el banco.
