### ISSUE TITLE
PSD2 (Payment Services Directive 2)

### ISSUE THREAD

**Issue by ncarreno** [ssheduardo/redsys-laravel#44]
Me ha llegado un mail del banco sobre este cambio en los TPV de Redsys. https://www.cajamar.es/es/comun/psd2/e-commerce-psd2-nueva-politica-servicios-pago/

 ¿Esto afecta en algo a este package?

**Comment by ssheduardo** [comment]
Hola,
En principio parece que no, tendría que investigar más a fondo si afecta o no al módulo principal.

**Comment by markcanals** [comment]
Hola,
¿Sabéis algo sobre si es posible añadir los parámetros COF para la normativa PSD2 que entra en vigor en enero?

Dejo el enlace con la info para si a alguien le interesa:
https://docsbs.necomplus.net/tpv-virtual/tpv-virtual-redsys/instalaci%C3%B3n/manual-de-integraci%C3%B3n-redirecci%C3%B3n/adaptaciones-psd2/transacciones-iniciadas-por-el-comercio-mit/transacciones-mit-y-uso-de-tokenizaci%C3%B3n-pago-por-referencia/

**Comment by ssheduardo** [comment]
Hace referencia en una parte que el sistema tratará de insertarlo.

> Sólo en caso de omisión de dichos parámetros en las operaciones subsiguientes el propio TPV Virtual SIS hará lo posible por incorporar de forma automática la información de marcaje de uso adecuada e información adicional requerida según la marca de la tarjeta en base a lo indicado para la transacción original (p.ej.: id transacción original requerido para los pagos COF en Visa “DS_MERCHANT_COF_TXNID”)

De todas formas tengo que ver algún usuario test que alguien me deje para probar, que creo recordar los que tenian contratado el servicio tenían acceso a un FUC válido.

**Comment by markcanals** [comment]
> Hace referencia en una parte que el sistema tratará de insertarlo.
> 
> > Sólo en caso de omisión de dichos parámetros en las operaciones subsiguientes el propio TPV Virtual SIS hará lo posible por incorporar de forma automática la información de marcaje de uso adecuada e información adicional requerida según la marca de la tarjeta en base a lo indicado para la transacción original (p.ej.: id transacción original requerido para los pagos COF en Visa “DS_MERCHANT_COF_TXNID”)
> 
> De todas formas tengo que ver algún usuario test que alguien me deje para probar, que creo recordar los que tenian contratado el servicio tenían acceso a un FUC válido.

**Comment by markcanals** [comment]
Efectivamente, pero según tengo entendido para los pagos con referencia es obligatório enviarlos de forma manual. Estoy de acuerdo que habrá que probar también si para los pagos sin referencia se generan automáticamente.
¡Gracias por tu ayuda!

**Comment by ssheduardo** [comment]
Si tienes acceso a un usuario de prueba para confirmarlo y sino pues hacemos los cambios respectivos.

**Comment by markcanals** [comment]
Lo único que hice fué una clase que extendía a Tpv.php. Puse la variable _setParameters de tu librería como protected y en mi clase añadí tres funciones para pasar los nuevos parámetros COF. Me sería muy útil que hubiera una función pública (setParameters) para añadir parámetros a _setParameters directamente de forma manual sin tener que modificar la variable de tu librería. La otra opción es añadir directamente las tres funciones para los parámetros COF... Ya me comentarás tu opinión al respeto. ¡Un saludo!

**Comment by ssheduardo** [comment]
Pues mira que bien, si te ha funciona sería bueno implementarlo así ayudamos al resto, dime como te quedo para poder agregarlo o si quieres has un PR para integrarlo

**Comment by ssheduardo** [comment]
Bueno ya me he puesto manos a la obra para crear el método **setParameters** para que se puedan agregar nuevos parámetros aparte de los que ya vienen por defecto, por si les hace falta alguno nuevo.
