### ISSUE TITLE
Mi servidor PRO no encuentra la class TPV

### ISSUE THREAD

**Issue by robles1993** [ssheduardo/redsys-laravel#45]
Hola Eduardo, primero de todo darte las gracias por el gran trabajo que has hecho con el código, es una maravilla y de muy facil intuición pero quiero saber el por que en mi servidor LOCAL HOST cuando realizo la acción de usar tu código si que me funciona bien (a falta de que no tengo claves de redys pero si que me entra hasta redys para darme el error ) y en cambio si lo monto en el HOSTING de pago no me funciona.. no encuentro el sentido si me lo pudieses explicar me seria una gran ayuda, muchisimas gracias de ante mano.

PD: EL eror que me salta es el siguiente:  **Class tpv does not exist at /var/www/vhosts/xxxxxxx.servicio-online.net/infoibi.es/reserva_barcos/vendor/laravel/framework/src/Illuminate/Container/Container.php:809)** Yo al tener la version 8.11.2 doy por hecho que no debo declarar las clases en el app.php tal y como explicas en la guia de instalación

y el uso de la clase en redsys controller:

**use Ssheduardo\Redsys\Facades\Redsys;**

Laravel version = 8.11.2

**Comment by ssheduardo** [comment]
Has ejecutado lo de composer install en tu servidor??

**Comment by robles1993** [comment]
Si , pero de todos modos creo que el problema ahora que estoy viendo es el hosting, disculpa por la molestias, voy a configurar ciertas cosas y si veo que sigue sin funcionar te aclaro un poco con más detalle si era problema mio, si configuro bien todo lo del composer y funciona te lo notifico en este mismo hilo para que descartes mi pregunta?

**Comment by ssheduardo** [comment]
Vale, de todas formas si vez el fallo lo comentas aquí por si le sirve a otra persona.
