### ISSUE TITLE
Se puede verificar un pedido

### ISSUE THREAD

**Issue by xbfast** [ssheduardo/redsys-laravel#47]
Buenas, primero de todo agradecer vuestro trabajo.

Tengo todo la plataforma ya funcionando pero me gustaria poder recibir algún campo que me ayude a identificar el pedido así poderle modificar el estado del mismo. La respuesta que trae redsys no veo nada que pueda utilizar.

Redsys solo me devuelve esto:
"Ds_SignatureVersion" => ""
"Ds_MerchantParameters" => ""
"Ds_Signature" => ""

Como puedo identificar el pedido, gracias!

**Comment by ssheduardo** [comment]
Mira aquí https://github.com/ssheduardo/sermepa#obtener-un-array-con-todos-los-datos-asignados
