### ISSUE TITLE
PHP 8

### ISSUE THREAD

**Issue by sangar82** [ssheduardo/redsys-laravel#48]
Hola!

Gracias por el plugin!

Podrías hacer compatible el plugin con PHP 8?

Esta limitado por el composer.json a que funcione con 7.2

Muchas gracias!

**Comment by ssheduardo** [comment]
Hola,
En la clase base haré el cambio para PHP8, seguramente el fin de semana este realizado.
Gracias por el aporte.

**Comment by ssheduardo** [comment]
Disculpa, no me había dado cuenta que era para el paquete de Laravel, acabo de actualizarlo para que admita PHP8, puedes probarlo?

**Comment by sangar82** [comment]
Perdona! No lo he podido probar todavía ya que maté la maquina virtual que tenía de pruebas ya que no podía seguir. En cuanto tenga un rato me pongo y si funciona, te agradecería si pudieras crear un tag nuevo.

Muchas gracias!

**Comment by ssheduardo** [comment]
> Perdona! No lo he podido probar todavía ya que maté la maquina virtual que tenía de pruebas ya que no podía seguir. En cuanto tenga un rato me pongo y si funciona, te agradecería si pudieras crear un tag nuevo.
> 
> Muchas gracias!

Al final he puesto que sea 7.X or 8.0, en principio debería funcionar para 7 y 8
