### ISSUE TITLE
Pago por Bizum

### ISSUE THREAD

**Issue by ncarreno** [ssheduardo/redsys-laravel#49]
Creo que ahora en Redsys se puede configurar el pago por Bizum. ¿se puede configurar pago por Bizum con este package?

**Comment by ssheduardo** [comment]
Pues ahí me pillas, voy a investigar el tema.
Si tienes documentación sobre ello me lo envías y lo veo.

**Comment by ncarreno** [comment]
Aquí le lo envío

[9999_TPV-Virtual Guia de Integracion BIZUM comercios SIS.PDF](https://github.com/ssheduardo/redsys-laravel/files/5950241/9999_TPV-Virtual.Guia.de.Integracion.BIZUM.comercios.SIS.PDF)

**Comment by ssheduardo** [comment]
Perfecto que tenga un hueco me pongo a verlo.
Gracias.

**Comment by ncarreno** [comment]
No se se falta algo más. Yo le paso en el setMethod la valor z y me llega bien a Bizum pero meto el teléfono de prueba y me da un error que no entiendo a que se debe porque el resto de datos están bien.

**Comment by ssheduardo** [comment]
Tienes los datos de prueba que te pasa el Banco para poder probarlo?

**Comment by andcl** [comment]
Hola, os puedo decir que, al menos con los datos del TPV de pruebas que Redsys pone a disposición del público, añadiendo `Redsys::setMethod('z');` en la petición, el pago se encamina por Bizum sin ningún problema :)

**Comment by ssheduardo** [comment]
> Hola, os puedo decir que, al menos con los datos del TPV de pruebas que Redsys pone a disposición del público, añadiendo `Redsys::setMethod('z');` en la petición, el pago se encamina por Bizum sin ningún problema :)

Para las pruebas creo que en su momento lo cambiaron y solo te daban un usuario de prueba si tenias contratado el servicio, sigue siendo así.
Es que necesito ir probando las cosas nuevas que van sacando.

**Comment by ncarreno** [comment]
> Hola, os puedo decir que, al menos con los datos del TPV de pruebas que Redsys pone a disposición del público, añadiendo `Redsys::setMethod('z');` en la petición, el pago se encamina por Bizum sin ningún problema :)

Yo hasta la pantalla del banco llego pero después cuando intento hacer el pago con el teléfono de prueba que pone la documentación me lleva a una pantalla de error.

**Comment by reina3596** [comment]
Yo os aporto mi experiencia. A mi resulta que en test no me funciona, pero si activas el modo live funciona sin problemas (obviamente con un teléfono real). El entorno de test de bizum no lo tienen muy pulido, pero si hacéis el proceso como os digo activando el modo live, lo veréis funcionando correctamente.

**Comment by andcl** [comment]
> Yo os aporto mi experiencia. A mi resulta que en test no me funciona, pero si activas el modo live funciona sin problemas (obviamente con un teléfono real). El entorno de test de bizum no lo tienen muy pulido, pero si hacéis el proceso como os digo activando el modo live, lo veréis funcionando correctamente.

Exacto, eso mismo me pasa a mí.

**Comment by jujerez** [comment]
El modo test funciona pero solo en producción, en el servidor local no funciona.

**Comment by ssheduardo** [comment]
@jujerez puedes dar más detalles para que quede claro al resto de usuarios.
Graias por tu aporte.

**Comment by jujerez** [comment]
Para que funcionara solo tuve que modificar Redsys::setMethod('z'), cuando hice las pruebas en mi servidor local es cierto que te redirige a una pantalla de error informandote de que no se ha podido procesar el pago, pero cuando lo probé en el servidor remoto si que funcionó, todo esto con Redsys:SetEnviromet('test')

**Comment by ssheduardo** [comment]
Gracias
