### ISSUE TITLE
Urls de notificacion

### ISSUE THREAD

**Issue by sdjurado** [ssheduardo/redsys-laravel#5]
Hola Eduardo,

no soy capaz de hacer que me funcionen las url de notificación, me redirige a la url_ok cuando el cliente hace click en continuar pero no recibo ningún dato o no soy capaz de obtenerlos... me podrías ayudar?

**Comment by ssheduardo** [comment]
Recuerda que la url de notificación debe ser valida para que el banco lea dicha url y te envié ahí todos los datos.

**Comment by sdjurado** [comment]
Gracias por contestar, la url es válida, el problema es que solo soy capaz de obtener el token y el laravelsession pero ningún parámetro... algo estoy haciendo mal pero no soy capaz de ver que es por mas vueltas que le doy.

**Comment by ssheduardo** [comment]
Como lo estas realizando?

**Comment by sdjurado** [comment]
El Routes.php lo tengo de la siguiente forma, lo he intentado tambien con Route::post en vez de get pero en ese caso me da error 405 method not allowed.

Route::get('/redsys_notificacion', ['as' => 'redsys', 'uses' => 'RedsysController@getNotificacion']);
Route::get('/redsys_ok', 'RedsysController@getURLOK'); 
Route::get('/redsys_ko', 'RedsysController@getURLKO'); 

me redirige bien a la pagina redsys_ok, pero ya te digo no obtengo ningún parámetro, o al menos eso es lo que observo cuando hago debug del request o post...

**Comment by ssheduardo** [comment]
Que raro, con un Route::post debería inyectar sin problemas dado que el banco hace una llamada a dicha url y te pasa por POST los datos, solo por probar usa:
```
Route::any('/redsys_notificacion', function () {
    //Guardar los datos en un log por ejemplo Log
    \Log::info('Variables ' .$_POST );
});
```

Creo que algo así debería funcionar (no estoy delante de un proyecto con laravel para probar en real)

**Comment by sdjurado** [comment]
No te preocupes, yo voy probando y te voy diciendo. Muchas gracias por la ayuda, en cuanto pruebe te comento ok?

**Comment by ssheduardo** [comment]
Si, así lo agregamos al README

**Comment by sdjurado** [comment]
Probé lo que me dijiste y esto es lo que me aparece en el log:


[2016-11-22 11:05:08] local.ERROR: Illuminate\Session\TokenMismatchException in /var/www/html/proyecto/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php:53
Stack trace:
#0 [internal function]: Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#1 /var/www/html/proyecto/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#2 /var/www/html/proyecto/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#3 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#4 /var/www/html/proyecto/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#5 /var/www/html/proyecto/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(62): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#6 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#7 /var/www/html/proyecto/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#8 /var/www/html/proyecto/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#9 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#10 /var/www/html/proyecto/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#11 /var/www/html/proyecto/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#12 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#13 /var/www/html/proyecto/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#14 /var/www/html/proyecto/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(44): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#15 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#16 /var/www/html/proyecto/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#17 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#18 /var/www/html/proyecto/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#19 /var/www/html/proyecto/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(122): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#20 /var/www/html/proyecto/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(87): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#21 /var/www/html/proyecto/public/index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#22 {main}

**Comment by ssheduardo** [comment]
¿Es un usuario que ha hecho login?
Eso es debido a que no se esta pasando el token, que versión de Laravel usas?

**Comment by sdjurado** [comment]
Uso laravel 5.1, la ruta de la notificación está fuera del middleware auth, ya que si lo incluía también fallaba, según los de redsys por error de usuario y contraseña...

**Comment by sdjurado** [comment]
Tengo puesto esto en el header, que según leí por ahí podría solucionar el problema del token:

<meta name="csrf-token" content="{{ csrf_token() }}" />

**Comment by sdjurado** [comment]
meta name="csrf-token" content="{{ csrf_token() }}"

**Comment by ssheduardo** [comment]
Pero la llamada lo hace el banco y no envía ese parámetro en Laravel 5.3 esta la opción de no requerir el token, pero para versiones anteriores existe X formas de hacerlo.

**Comment by sdjurado** [comment]
Ok, voy a investigar. Te comento cuando sepa algo. Gracias.

**Comment by sdjurado** [comment]
Solucionado!! había que excluir la verificación de token en las rutas de notificación, añadiendo dichas rutas en middleware VerifyCsrfToken.php añadiéndolas en la variable $except:

protected $except = [
    	//'ruta',
];

**Comment by ssheduardo** [comment]
Genial @sdjurado, que versiónde Laravel usas, más que todo para si alguno le pasa lo mismo.

**Comment by sdjurado** [comment]
Laravel 5.1, ya estaba indicado en una de las respuestas anteriores ;)

**Comment by ssheduardo** [comment]
Toda la razón, se me ha ido.
