### ISSUE TITLE
Compatibilidad lumen

### ISSUE THREAD

**Issue by alesanderlopez** [ssheduardo/redsys-laravel#50]
Buenas,

Abro esta consulta para saber si la librería sería compatible con lumen.

Tengo una plataforma en NodeJS y querría hacer un microservicio externo con lumen e implementar la librería.

Usaría lumen porque no necesito muchas herramientas de Laravel nativo y por su ligereza.

Un saludo,

**Comment by ssheduardo** [comment]
La verdad es que no he usado Lumen pero he visto esto que tal vez pueda ayudarte

https://github.com/irazasyed/larasupport

**Comment by alesanderlopez** [comment]
Vaya muchísimas gracias, probaré con ese paquete a ver que tal.

Si me va todo correcto te informo por si te interesa si no intentaré hacer un fork o probar con otras alternativas. 

Un saludo,
