### ISSUE TITLE
Php version 8 no detectada en composer.json

### ISSUE THREAD

**Issue by andcl** [ssheduardo/redsys-laravel#51]
Hola Eduardo, 
Al intentar instalar tu paquete con `composer require "ssheduardo/redsys-laravel=~1.4.0"`, composer me tira el siguiente error:
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - ssheduardo/redsys-laravel[1.4.0, ..., 1.4.2] require php ^7.2 -> your php version (8.0.1) does not satisfy that requirement.
    - Root composer.json requires ssheduardo/redsys-laravel ~1.4.0 -> satisfiable by ssheduardo/redsys-laravel[1.4.0, 1.4.1, 1.4.2].
```
Mi entorno, como puedes ver, ejecuta PHP 8. 
Se me ocurre que pueda ser cómo lo has definido en tu composer.json, ya que parece que sólo detecta el php 7.2, y no el 8.0.
Te ocurre a ti lo mismo en un entorno php8?

Gracias de antemano.

**Comment by ssheduardo** [comment]
Hola,
Toda la razón, ahora lo veo.

**Comment by ssheduardo** [comment]
Vale parece que ya esta.
Si puedes probarlo cuando puedas.

**Comment by andcl** [comment]
Efectivamente, corregido.
Muchas gracias.
