### ISSUE TITLE
Problema con Url_notification

### ISSUE THREAD

**Issue by Alicia-ls** [ssheduardo/redsys-laravel#55]
Hola! Tengo el botón de pagar ahora que redirecciona a Redsys dentro de un form. El problema está en que si en el action de ese form le pongo la función de comprobar, me devuelve null porque coge el primer submit de todos, cuando el que yo quiero que coja es el de después de pagar. 

Entonces, me gustaría que me aclarase en qué momento llamo a la función de comprobar. 

Gracias.

**Comment by ssheduardo** [comment]
Esa comprobación se hace cuando le pasas en el parámetro de URL_NOTIFICATION , es el banco que automáticamente leerá esa url y te enviará todo el resultado.
