### ISSUE TITLE
Error en el formulario de la pasarela de pago al hacer click en "Aceptar"

### ISSUE THREAD

**Issue by BryanPlaces** [ssheduardo/redsys-laravel#58]
Buenas tardes, en el formulario del redsys tengo el siguiente error despues de añadir los campos de la tarjeta y al hacer click en "aceptar" me salta el siguiente error "Uncaught TypeError: document.getElementById(...) is null". Salta en el archivo **RSisSelPagosNew.js** en la funcion **estiloBotonPagar()** en esta linea **document.getElementById('divImgCancelar').disabled = true;**

Estoy usando laravel 5.7 y redsys-laravel 1.3, no encuentro la forma de solucionarlo, en principio la integración esta bien, no realiza la llamada al url_notification y el unico error que me muestra es el mensionado previamente.

Un saludo y gracias

**Comment by ssheduardo** [comment]
Una pregunta estas usando Redsys InSite??

**Comment by ssheduardo** [comment]
Pero es en la pantalla del Banco donde te pide la tarjeta?

**Comment by BryanPlaces** [comment]
Si, es en ese formulario, da igual la tarjeta que use o la información que añada me sale el mensaje de error que puse al principio

**Comment by ssheduardo** [comment]
Si es en la pantalla del Banco es problema del Banco.
Adjunto capturas de todas formas.
