### ISSUE TITLE
Function mcrypt_encrypt() is deprecated in php7.1

### ISSUE THREAD

**Issue by juanmalopez** [ssheduardo/redsys-laravel#6]
Hola Eduardo,

El modulo de php mcrypt esta deprecated en la version 7.1 de php, ya que cuando se ejecuta la función "mcrypt_encrypt" dentro del codigo, se genera el siguiente error:

"Function mcrypt_encrypt() is deprecated"

He encontrado esta posible solución en otro paquete:

- https://github.com/opencart/opencart/issues/5126

Muchas gracias

**Comment by ssheduardo** [comment]
Parece que se tiene que usar openssl_encrypt
https://github.com/eka7a/opencart/commit/040d6baef56deb57b8f6388e988d15f5d24e82fc
Hoy investigo a ver si funciona todo.
Gracias @juanmalopez

**Comment by juanmalopez** [comment]
Gracias por contestar

**Comment by ssheduardo** [comment]
Ya esta actualizado, la clase base Tpv.php  fue actualizada y probada con php 7.0, se cambio *mcrypt_encrypt* por *openssl_encrypt*
Si puedes realizar más pruebas sería genial.

**Comment by juanmalopez** [comment]
He realizado varias pruebas con la nueva versión, y ha funcionado correctamente.
Muchas gracias @ssheduardo

**Comment by ssheduardo** [comment]
Gracias @juanmalopez,
Procedo a cerrar ticket
