### ISSUE TITLE
Como se puede activar la tokerizacion en redsys-laravel?

### ISSUE THREAD

**Issue by pj-arenas** [ssheduardo/redsys-laravel#60]
como puedoactivar la tokerizacion, no me devuelve ningun token para guardarlo y hacer un pago recurrente

**Comment by ssheduardo** [comment]
Tienes que hablar con tu banco para que habiliten la tokenización.

**Comment by PedroJoseAP** [comment]
y entonces cada vez que haga el pago me devolvera el token?, y luego para pagar como pagaria con ese token ?

**Comment by PedroJoseAP** [comment]
Perfecto muchas gracias, y para pagar con esa referencia y hacer un pago recurrente, hay alguna función predefinida'

**Comment by ssheduardo** [comment]
En el README puedes ver algunas cosas que se detallan.

**Comment by PedroJoseAP** [comment]
vale perfecto gracias

**Comment by PedroJoseAP** [comment]
Buenas he estado mirando y no hay nada en la documentacion de redsys-laravel, para hacer un pago recurrente solo para hacer un pago normal

**Comment by ssheduardo** [comment]
El paquete laravel redsys se apoya de https://github.com/ssheduardo/sermepa, dentro puedes ver los ejemplos.

**Comment by PedroJoseAP** [comment]
para laravel 5.5 tambien se apoya en este?

**Comment by ssheduardo** [comment]
En principio si.

**Comment by PedroJoseAP** [comment]
nopuede ser porque me falte algun parametro, tengo esto dentro de mi try:    Redsys::setAmount($request->amount);
            Redsys::setOrder(time ());
            Redsys::setMerchantcode($code); //Reemplazar por el código que proporciona el banco
            Redsys::setCurrency('978');
            Redsys::setTransactiontype('0');
            Redsys::setTerminal('100');
            Redsys::setIdentifier($request->payment_token);
            Redsys::setVersion( 'HMAC_SHA256_V1');
            Redsys::setEnviroment('test'); //Entorno test si quieres usar  entorno de produccion usa 'live'
            Redsys::setMerchantCofIni('N');
            Redsys::setMerchantCofTxnid(2202172334011);
            Redsys::setExpiryDate('3412');
           
            Redsys::setMethod( 'T'); //Solo pago con tarjeta, no mostramos iupay
            Redsys::setNotification (config ('redsys.url_notification' )); //Url de notificacion
            Redsys::setUrlOk(config('redsys.url_ok'));                   
            Redsys::setUrlKo(config('redsys.url_ko'));                                                   
            Redsys::setVersion( 'HMAC_SHA256_V1');
            Redsys::setTradeName('TRAINING , SL');
            Redsys::setTitular($headline);
            Redsys::setProductDescription('2023 MENSUAL');//se pondra el description pero hay que actualizar la bdd
            Redsys::setEnviroment('test'); //Entorno test si quieres usar  entorno de produccion usa 'live'
            Redsys::setIdentifier($request->payment_token);

            Redsys::setMerchantDirectPayment(true);
           // Redsys::setAttributesSubmit('btn_submit', 'btn_id', 'Pagar');

            $signature = Redsys::generateMerchantSignature($key);
            Redsys::setMerchantSignature($signature);

            Redsys::executeRedirection();

**Comment by ssheduardo** [comment]
Tienes que consultar con el Banco por si no tienes algo activado o te falta algún parámetro.

![image](https://github.com/ssheduardo/redsys-laravel/assets/1160138/27211ad8-8a31-40cb-a927-701c4c884fdb)

En caso tengas las solución comentarlo aquí por si le sirve a alguien.

**Comment by PedroJoseAP** [comment]
el banco me ha dicho que esta todo activado, que lo que pasa es que no estoy enviando DS_MERCHANT_EXCEP_SCA":"MIT"} pero no encuentro ninguna funcion de sermepa en la documentacion para enviar esto
