### ISSUE TITLE
Este paquete sirve para hacer pagos recurrentes?

### ISSUE THREAD

**Issue by IonAtomico** [ssheduardo/redsys-laravel#62]
Este paquete sirve para hacer pagos recurrentes?

**Comment by IonAtomico** [comment]
Este paquete sirve para hacer pagos recurrentes?

**Comment by ssheduardo** [comment]
Tienes a la mano todos los métodos, es cuestión de ver como lo solicita el banco y pasar esos parámetros con esta clase.

**Comment by IonAtomico** [comment]
Perfecto, gracias
