### ISSUE TITLE
RESPUESTA ANTES DE DARLE AL BOTON CONTINUAR ??

### ISSUE THREAD

**Issue by mgip** [ssheduardo/redsys-laravel#65]
Hola, cuando sale el formulario de redsys, se introduce la tarjeta y luego se le da a pagar, procesa el pago, luego se le tiene que dar continuar para que redsys devuelva la respuesta a la URL OK o KO, el problema que veo es que necesito la respuesta antes que se le de a continuar, eso ocurre porque muchos no le dan a continuar, muchos usuarios al ver la notificacion en verde ya lo dan como pagado, pero mi aplicacion no se entera de la respuesta, si se logra ver si fue OK o KO por canales, pero la idea es que el app reciba la informacion porque es un sistema de reservas. Lo estoy desarrollando en Laravel 9.

¿Es posible?, lo otro que estuve leyendo fue usar el API REST, pero me surge una duda, como gestiona los pagos que requieren la autorizacion del banco, como sms o gestionarla via app (del banco), porque via pasarale redsys como lo tengo ahorita, si sale el html del banco. 

De verdad estoy que me vuelvo loco, no encuentro informacion al respecto. 

Gracias de antemano por la ayuda.

**Comment by miguel-heredia** [comment]
Buenas, eso te lo activa el servicio técnico de redsys. Contactas con ellos, les dices que quieres que esa parte del proceso sea automático y listo.

**Comment by dualklip** [comment]
También se puede utilizar este proceso de comprobación, pero tienes que dispararlo tu:

```php
try{
    $redsys = new Sermepa\Tpv\Tpv();
    $key = 'sq7HjrUOBfKmC576ILgskD5srU870gJ7';

    $parameters = $redsys->getMerchantParameters($_POST["Ds_MerchantParameters"]);
    $DsResponse = $parameters["Ds_Response"];
    $DsResponse += 0;
    if ($redsys->check($key, $_POST) && $DsResponse <= 99) {
        //acciones a realizar si es correcto, por ejemplo validar una reserva, mandar un mail de OK, guardar en bbdd o contactar con mensajería para preparar un pedido
    } else {
        //acciones a realizar si ha sido erroneo
    }
} catch (\Sermepa\Tpv\TpvException $e) {
    echo $e->getMessage();
}
```

Fuente: https://github.com/ssheduardo/sermepa?tab=readme-ov-file#comprobaci%C3%B3n-de-pago
