### ISSUE TITLE
function check y pagos correctos

### ISSUE THREAD

**Issue by arofe** [ssheduardo/redsys-laravel#7]
La función check solo comprueba si la notificación viene del banco.

Sería interesante que comprobase si el pago ha sido correcto.
O hacer una nueva función que lo compruebe.

El parámetro a comprobar si el pago es correcto es 'DS_Response' con '0000', 'Ds_AuthorisationCode'.

Gracias, saludos.

**Comment by ssheduardo** [comment]
Hola @arofe,
Efectivamente el método check no cumple dicha función de ver que un pago es correcto, en la url https://github.com/ssheduardo/sermepa#comprobación-de-pago puedes ver que se captura el valor de **DS_Response** y se valida conjuntamente con el método **check**
