### ISSUE TITLE
redsys.url_notification

### ISSUE THREAD

**Issue by esedArk** [ssheduardo/redsys-laravel#8]
Hola!

Tengo una pregunta, cuando hace llamada de redsys.url_notification ? ahí es lo que nos dice el callback de que el pago está Ok o no Ok vdd?

Leyendo otra issue que un compañero le ha pasado lo mismo, he hecho lo mismo que él hacía y nada. Yo tengo el CSFR desactivado pero no recibo ninguna petición por el banco...

**Comment by esedArk** [comment]
Nada! Ya está arreglado... al no recibir post por parte de redsys miré en su panel de control y era fallos suyo... lo siento y gracias va todo perfecto!

**Comment by ssheduardo** [comment]
De nada
